/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:810562:
  //println("textfield1 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:textfield1:810562:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:947736:
  sg.push(textfield1.getText() );
} //_CODE_:button1:947736:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:626290:
  sg.pop();
} //_CODE_:button2:626290:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("stack demo");
  textfield1 = new GTextField(this, 13, 21, 160, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  button1 = new GButton(this, 213, 18, 80, 30);
  button1.setText("add");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 323, 18, 80, 30);
  button2.setText("remove");
  button2.addEventHandler(this, "button2_click1");
}

// Variable declarations 
// autogenerated do not edit
GTextField textfield1; 
GButton button1; 
GButton button2; 
